listen=YES
local_enable=YES
local_umask=0002
write_enable=YES

rsa_cert_file=/etc/ssl/certs/ssl.crt
rsa_private_key_file=/etc/ssl/certs/ssl.key
ssl_enable=YES
allow_anon_ssl=NO
force_local_data_ssl=YES
force_local_logins_ssl=YES
ssl_tlsv1=YES
ssl_sslv2=NO
ssl_sslv3=NO
syslog_enable=YES
require_ssl_reuse=NO
ssl_ciphers=HIGH

pasv_enable=Yes
pasv_max_port=21110
pasv_min_port=21100
pasv_addr_resolve=NO

